name: Generate Snake

on:
  schedule:
    - cron: "0 0 * * *"

  workflow_dispatch:

permissions:
  contents: write

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - name: Generate contribution snake
        uses: Platane/snk@v3
        with:
          github_user_name: Cachorreira
          outputs: |
            dist/github-contribution-grid-snake.svg?color_snake=#00FF88&color_dots=#161B22,#0E4429,#006D32,#00A83B,#00FF88
            dist/github-contribution-grid-snake-dark.svg?palette=github-dark&color_snake=#00FF88&color_dots=#161B22,#0E4429,#006D32,#00A83B,#00FF88

      - name: Publish Snake animation
        uses: crazy-max/ghaction-github-pages@v4
        with:
          build_dir: dist
        env:
          GH_PAT: ${{ secrets.GITHUB_TOKEN }}
